from music_manger.implementations import RocknationAndSpotify as _RocknationAndSpotify
from music_manger.implementations import MockMusicManager as _MockMusicManager

music_manager_impl = _RocknationAndSpotify
